# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-22 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('browse', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf')),
                ('status', models.IntegerField(default=0, verbose_name='\u6587\u7ae0\u72b6\u6001\uff0c0\uff1a\u5b58\u5728\uff0c1\uff1a\u5df2\u5220\u9664')),
                ('update_time', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=64, verbose_name='\u6b63\u5219URL')),
                ('feature', models.CharField(max_length=16, verbose_name='\u529f\u80fd')),
            ],
            options={
                'verbose_name_plural': '\u6743\u9650\u8868',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=16, verbose_name='\u89d2\u8272\u540d')),
                ('permissions', models.ManyToManyField(blank=True, to='backend.Permission', verbose_name='\u6743\u9650')),
            ],
            options={
                'verbose_name_plural': '\u89d2\u8272\u8868',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u6807\u7b7e\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
                ('roles', models.ManyToManyField(blank=True, to='backend.Role', verbose_name='\u89d2\u8272')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='\u6587\u7ae0\u4f5c\u8005id'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='backend.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
